- name: install nginx
  apt: name=nginx state=present
  tags: nginx

- name: Template nginx conf
  template: src=default.conf.j2 dest={{ nginx_path }}/nginx.conf
  tags: nginx

- name: Template https-redirect conf
  template: src=https-redirect.conf.j2 dest={{ nginx_path }}/sites-enabled/default
  tags: nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted
