version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/signup-back"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/signup-front"
    schedule:
      interval: "weekly"
