- hosts: signup,api-scopes,api-auth
  become: true
  roles:
    - app-user
    - role: team-ssh-keys
      tags: team-ssh-keys
    - nginx
    - role: ansible-role-nodejs
      nodejs_version: 8.x

- hosts: signup
  become: true
  roles:
    - role: ruby
      tags: ruby
    - role: ssl
      server_name: "{{ back_domain_name }}"
    - role: ssl
      server_name: "{{ front_domain_name }}"
    - role: postgres
      pg_user: back
      pg_password: "{{ back_pg_password }}"
      pg_database: signup-back
      tags:
      - back
    - role: rails-app
      app_service_name: signup-back
      server_name: "{{ back_domain_name }}"
      app_port: 3000
      pg_user: back
      pg_password: "{{ back_pg_password }}"
      pg_database: signup-back
      devise_secret: "{{ back_devise_secret }}"
      secret_key_base: "{{ back_secret_key_base }}"
      env_var:
        SERVER_NAME: "{{ inventory_hostname }}"
        PORT: "{{ app_port }}"
        FRONT_HOST: "{{ front_host }}"
        BACK_HOST: "{{ back_host }}"
        OAUTH_REDIRECT_URI: "{{ oauth_redirect_uri }}"
        OAUTH_HOST: "{{ oauth_host }}"
        DEVISE_SECRET: "{{ devise_secret }}"
        SECRET_KEY_BASE: "{{ secret_key_base }}"
        PG_USER: "{{ pg_user }}"
        PG_PASSWORD: "{{ pg_password }}"
        PG_DATABASE: "{{ pg_database }}"
        SIGNUP_OAUTH_CLIENT_ID: "{{ signup_oauth_client_id }}"
        SIGNUP_OAUTH_CLIENT_SECRET: "{{ signup_oauth_client_secret }}"
        ENABLE_REGISTER_FRANCECONNECT_ENROLLMENT: "{{ enable_register_franceconnect_enrollment }}"
        FRANCECONNECT_PARTICULIER_HOST: "{{ franceconnect_particulier_host }}"
        FRANCECONNECT_PARTICULIER_API_KEY: "{{ franceconnect_particulier_api_key }}"
        API_PARTICULIER_HOST: "{{ api_particulier_host }}"
        API_PARTICULIER_API_KEY: "{{ api_particulier_api_key }}"
        MAILJET_API_KEY: "{{ mailjet_api_key }}"
        MAILJET_SECRET_KEY: "{{ mailjet_secret_key }}"
        DO_NOT_SEND_MAIL: "{{ do_not_send_mail | default('') }}"
        API_SCOPES_DOMAIN_NAME: "{{ api_scopes_domain_name }}"
        API_SCOPES_DATABASE_NAME: "{{ api_scopes_database_name }}"
        API_SCOPES_DATABASE_PORT: "{{ api_scopes_database_port }}"
        API_SCOPES_READWRITE_USER: "{{ api_scopes_readwrite_user }}"
        API_SCOPES_READWRITE_PASSWORD: "{{ api_scopes_readwrite_password }}"
      tags:
      - back
      - app-config
    - role: node-app
      app_service_name: signup-front
      server_name: "{{ front_domain_name }}"
      app_port: 3002
      env_var:
        OAUTH_AUTHORIZE_URI: "{{ oauth_authorize_uri }}"
        OAUTH_ME_URI: "{{ oauth_me_uri }}"
        OAUTH_HOST: "{{ oauth_host }}"
        BACK_HOST: "{{ back_host }}"
        API_PARTICULIER_HOST: "{{ api_particulier_host }}"
        PIWIK_URL: "{{ piwik_url | default('') }}"
        PIWIK_SITE_ID: "{{ piwik_site_id | default('') }}"
      tags:
      - front
      - app-config

- hosts: api-scopes
  become: true
  roles:
    - role: ssl
      server_name: "{{ api_scopes_domain_name }}"
    - role: mongodb
      tags: mongodb
    - role: node-app
      app_service_name: api-scopes
      server_name: "{{ api_scopes_domain_name }}"
      app_port: 3000
      env_var:
        API_SCOPES_DOMAIN_NAME: "{{ api_scopes_domain_name }}"
        API_SCOPES_DATABASE_NAME: "{{ api_scopes_database_name }}"
        API_SCOPES_DATABASE_PORT: "{{ api_scopes_database_port }}"
        API_SCOPES_API_SCOPES_USER: "{{ api_scopes_api_scopes_user }}"
        API_SCOPES_API_SCOPES_PASSWORD: "{{ api_scopes_api_scopes_password }}"
      tags:
        - api-scopes
        - app-config

- hosts: api-auth
  become: true
  roles:
    - role: ssl
      server_name: "{{ api_auth_domain_name }}"
    - role: postgres
      pg_user: api-auth
      pg_password: "{{ api_auth_pg_password }}"
      pg_database: api-auth
    - role: redis
      tags: redis
    - role: node-app
      app_service_name: api-auth
      server_name: "{{ api_auth_domain_name }}"
      app_port: 3000
      env_var:
        PGUSER: api-auth
        PGPASSWORD: "{{ api_auth_pg_password }}"
        PGDATABASE: api-auth
        PGPORT: 5432
        DATABASE_URL: "postgres://api-auth:{{ api_auth_pg_password }}@127.0.0.1:5432/api-auth"
        MAILJET_API_KEY: "{{ mailjet_api_key }}"
        MAILJET_SECRET_KEY: "{{ mailjet_secret_key }}"
        API_AUTH_HOST: "https://{{ api_auth_domain_name }}"
        DO_NOT_SEND_MAIL: "{{ do_not_send_mail | default('') }}"
        SESSION_COOKIE_SECRET: "{{ session_cookie_secret }}"
        OIDC_PAIRWISE_IDENTIFIER_SALT: "{{ oidc_pairwise_identifier_salt }}"
      tags:
        - api-auth
        - app-config
