- hosts: apps
  become: true
  roles:
    - app-user
    - role: team-ssh-keys
      tags: team-ssh-keys
    - nginx
    - role: ansible-role-nodejs
      nodejs_version: 8.x
    - ruby

- hosts: back
  become: true
  roles:
    - ssl
    - role: rails-app
      tags:
        - back
        - app-config

- hosts: oauth
  become: true
  roles:
    - ssl
    - role: rails-app
      tags:
        - oauth
        - app-config

- hosts: front
  become: true
  roles:
    - ssl
    - role: node-app
      tags:
        - front
        - app-config
