- hosts: datapass-front
  vars:
    ansible_user: "{{ app_user }}"
  tasks:
    - name: deploy front
      script: ./scripts/deploy-static-app.sh signup-front
      tags:
        - front

- hosts: datapass-back
  vars:
    ansible_user: "{{ app_user }}"
  tasks:
    - name: deploy back
      script: ./scripts/deploy-server-app.sh signup-back
      tags:
        - back

- hosts: api-auth
  vars:
    ansible_user: "{{ app_user }}"
  tasks:
    - name: deploy api-auth
      script: ./scripts/deploy-server-app.sh api-auth
      tags:
        - api-auth
