- hosts: signup
  vars:
    ansible_user: "{{ app_user }}"
  tasks:
  - name: deploy front
    script: ./scripts/deploy.sh signup-front
    tags:
    - front
  - name: deploy back
    script: ./scripts/deploy.sh signup-back
    tags:
    - back

- hosts: api-auth
  vars:
    ansible_user: "{{ app_user }}"
  tasks:
  - name: deploy api-auth
    script: ./scripts/deploy.sh api-auth
    tags:
    - api-auth
