- hosts: back
  become: true
  tasks:
    - name: deploy back
      script: ./scripts/deploy.sh signup.api.gouv.fr-back
      tags:
        - back
      become_user: "{{ app_user }}"
    - name: restart service
      service:
        name: signup.api.gouv.fr-back
        state: restarted

- hosts: oauth
  become: true
  tasks:
    - name: deploy oauth
      script: ./scripts/deploy.sh signup.api.gouv.fr-oauth
      tags:
        - oauth
      become_user: "{{ app_user }}"
    - name: restart service
      service:
        name: signup.api.gouv.fr-oauth
        state: restarted
