- src: zzet.rbenv
  version: "3.3.6"
- src: https://github.com/thefinn93/ansible-letsencrypt
- src: https://github.com/geerlingguy/ansible-role-nodejs
- src: libre_ops.metabase
- src: devoinc.openjdk
