- name: restart nginx
  service:
    name: nginx
    state: restarted

# TODO dynamically generate these handlers
- name: "restart service signup-back"
  service:
    name: signup-back
    state: restarted

- name: "restart service sidekiq-signup-back"
  service:
    name: sidekiq-signup-back
    state: restarted
