- include: install-ruby.yml

- name: install postgresql
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - postgresql
    - python-psycopg2

- name: install yarn
  npm:
    name: yarn
    global: yes
    state: present

- name: create oauth postgresql user
  postgresql_user:
    name: "{{ oauth_pg_user }}"
    password: "{{ oauth_pg_password }}"
  become_user: postgres

- name: create oauth db
  postgresql_db:
    name: "{{ oauth_pg_db }}"
    owner: "{{ oauth_pg_user }}"
  become_user: postgres

- name: ensure app_user group exists
  group:
    name: "{{ app_user }}"
    state: present

- name: ensure app_user user exists
  user:
    name: "{{ app_user }}"
    group: "{{ app_user }}"
    state: present

- name: create app directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  with_items:
    - /opt/apps
    - /opt/apps/signup.api.gouv.fr-oauth

- name: copy configuration file
  template:
    src: signup.api.gouv.fr-oauth.conf.j2
    dest: /etc/signup.api.gouv.fr-oauth.conf
  notify: restart service

- name: copy systemd file
  template:
    src: signup.api.gouv.fr-oauth.service.j2
    dest: /etc/systemd/system/signup.api.gouv.fr-oauth.service
  notify: restart service

- name: enable services
  systemd:
    name: signup.api.gouv.fr-oauth
    enabled: true
    daemon_reload: yes
    state: started

- name: configure nginx
  template:
    src: oauth.api.gouv.fr.conf.j2
    dest: /etc/nginx/sites-enabled/oauth.api.gouv.fr
  notify: restart nginx
