- name: initialize
  file:
    path: /opt/apps/{{app_name}}/
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: unarchive new version  {{app_name}}-{{ app_version }}
  unarchive:
    copy: no
    src: "https://github.com/betagouv/{{app_name}}/archive/{{ app_version }}.tar.gz"
    dest: /opt/apps/{{app_name}}/
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: install gem dependencies
  shell: bundle install
  args:
    chdir: /opt/apps/{{ app_name }}/signup.api.gouv.fr-oauth-{{ app_version }}

- name: install node dependencies
  shell: yarn install
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/lib/npm/bin"
  args:
    chdir: /opt/apps/{{ app_name }}/signup.api.gouv.fr-oauth-{{ app_version }}
  become_user: "{{ app_user }}"

- name: Precompile assets
  shell: bundle exec rake assets:precompile RAILS_ENV=production
  args:
    chdir: /opt/apps/{{ app_name }}/signup.api.gouv.fr-oauth-{{ app_version }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/lib/npm/bin"
  become_user: "{{ app_user }}"

- name: create and migrate db
  shell: |
    bundle exec rake db:create db:migrate RAILS_ENV=production PG_USER={{ oauth_pg_user }} PG_PASSWORD={{ oauth_pg_password }} PG_DB={{ oauth_pg_db }} DEVISE_SECRET={{ devise_secret }}
  args:
    chdir: /opt/apps/{{ app_name }}/signup.api.gouv.fr-oauth-{{ app_version }}
  become_user: "{{ app_user }}"

- name: link new version
  file:
    force: yes
    state: link
    src: /opt/apps/{{ app_name }}/signup.api.gouv.fr-oauth-{{ app_version }}
    path: /opt/apps/{{ app_name }}/{{ app_name }}
    owner: "{{ app_user }}"

- name: restart service
  service:
    name: "{{ app_name }}"
    enabled: yes
    state: restarted
