- name: Install rails dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - ruby
    - ruby-dev
    - rubygems
    - libxslt-dev
    - libxml2-dev
    - liblzma-dev
    - zlib1g-dev
    - libmagickwand-dev
    - sqlite3
    - libsqlite3-dev
    - libpq-dev
- name: Install bundler
  shell: >
    gem install bundler
