---
- name: Generate self-signed certificates for {{ server_name }}
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Paris/L=Paris/O=IT/CN={{ server_name }}" -days 3650 -keyout {{nginx_path}}/ssl/{{server_name}}.key -out {{nginx_path}}/ssl/{{server_name}}.crt -extensions v3_ca
  notify: restart nginx
  args:
    creates: "{{nginx_path}}/ssl/{{server_name}}.crt"
