---
- name: Generate self-signed certificates for {{ ssl_certificate_host }}
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Paris/L=Paris/O=IT/CN={{ ssl_certificate_host }}" -days 3650 -keyout {{nginx_path}}/ssl/{{ssl_certificate_host}}.key -out {{nginx_path}}/ssl/{{ssl_certificate_host}}.crt -extensions v3_ca
  notify: restart nginx
  args:
    creates: "{{nginx_path}}/ssl/{{ssl_certificate_host}}.crt"
