- include: install-ruby.yml

- name: install postgresql
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - postgresql
    - python-psycopg2

- name: install yarn
  npm:
    name: yarn
    global: yes
    state: present

- name: create back postgresql user
  postgresql_user:
    name: "{{ back_pg_user }}"
    password: "{{ back_pg_password }}"
  become_user: postgres

- name: create back db
  postgresql_db:
    name: "{{ back_pg_db }}"
    owner: "{{ back_pg_user }}"
  become_user: postgres

- name: ensure app_user group exists
  group:
    name: "{{ app_user }}"
    state: present

- name: ensure app_user user exists
  user:
    name: "{{ app_user }}"
    group: "{{ app_user }}"
    state: present

- name: create app directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/apps
    - /opt/apps/signup.api.gouv.fr-back

- name: copy configuration file
  template:
    src: back.conf.j2
    dest: /etc/signup.api.gouv.fr-back.conf
  notify: restart service

- name: copy systemd file
  template:
    src: back.service.j2
    dest: /etc/systemd/system/signup.api.gouv.fr-back.service
  notify: restart service

- name: enable services
  systemd:
    name: signup.api.gouv.fr-back
    daemon_reload: yes
    enabled: true
    state: started

- name: configure nginx
  template:
    src: back.signup.api.gouv.fr.conf.j2
    dest: /etc/nginx/sites-enabled/back.signup.api.gouv.fr
  notify: restart nginx
